name: Build and Release Quiz Game

on:
  push:
    tags:
      - 'v*'   # v1.0.0 みたいなタグを push したときに動く
  workflow_dispatch: # 手動でも実行できる

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pygame

      - name: Build EXE
        run: pyinstaller --onefile quiz_game_gui.py

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/quiz_game_gui.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
